'use client';
import './globals.css';
import { Providers } from './providers';
import { Inter } from 'next/font/google';

import { Navbar } from '../components';
import { usePathname } from 'next/navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html
      data-testid='layout-page'
      lang='en'
      className={`${inter.className} dark bg-background`}>
      <body>
        <Providers>
          {!pathname.includes('/auth') && <Navbar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
