import './globals.css'
import { Providers } from "./providers"
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-testid='login-layout-page' lang="es" className={`${inter.className} dark bg-background`}>
      <body >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
